"""Network element catalog and @njit residual kernels."""

from .dynamic_source import (
    DynamicSource,
    DynamicResponseTerm,
    TransferFunction,
    NTau,
    NTauLowpass,
    Tabulated,
    Constant,
    n_tau,
    n_tau_lowpass,
    tabulated,
    constant,
    as_transfer,
    heat_release_response,
    mass_flow_response,
    n_tau_flame,
)
from .composite import (
    CompositeElementSpec,
    CompositeMap,
    GridRefinement,
    AutoRefinement,
    expand_composites,
    is_composite,
    grid_refine,
    auto_refine,
)

__all__ = [
    "CompositeElementSpec",
    "CompositeMap",
    "GridRefinement",
    "AutoRefinement",
    "expand_composites",
    "is_composite",
    "grid_refine",
    "auto_refine",
    "DynamicSource",
    "DynamicResponseTerm",
    "TransferFunction",
    "NTau",
    "NTauLowpass",
    "Tabulated",
    "Constant",
    "n_tau",
    "n_tau_lowpass",
    "tabulated",
    "constant",
    "as_transfer",
    "heat_release_response",
    "mass_flow_response",
    "n_tau_flame",
]
